{% set name = "mrcz" %}
{% set version = "0.4.1" %}
{% set sha256 = "bd73fa6306846b46a5186c394fed2275dde378b0da6fbdccd3ccd14b96250c73" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - python-blosc
    - futures  # [py2k]

test:
  imports:
    - mrcz

about:
  home: https://github.com/em-MRCZ/python-mrcz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python module for compressed MRCZ-file format'
  description: |
    mrcz is a package designed to supplement the venerable MRC image file format 
    with a highly efficient compressed variant, using the blosc meta-compressor 
    library to shrink files on disk and greatly accelerate file input/output 
    for the era of "Big Data" in electron and optical microscopy.
  doc_url: http://python-mrcz.readthedocs.io/
  dev_url: https://github.com/em-MRCZ/python-mrcz

extra:
  recipe-maintainers:
    - RobbMcleod
