travis:
  secure:
    BINSTAR_TOKEN: BFijXS7d8e7CAB9yc2tem04FeFbzFDwTBAR6F85RlWZw9C93pYcTqoGSeuzY2MpYCX00xOlcEpmj2ytpS5dokPslPINs5/owLtXqVQLfA3t8829zJZLdLjFPSXZiKlcWD2DCm1BMxvcYwY/bl2Nk5Lw062ed9oHH29Q88Y0QQUk6jnvTKP0PQ5j3ccJS8mTOlhoVF1brc9kif5UU5YP/QOn6lzcRT+m2N2Ns1XNtpUrN3Yj2Ais/JlzT3p2I3USX5nvAZy536bBYMA9T94I6mQUSfZkosYodRBMq39NTpsxY9KjfIzCaExec4M7y6paJ/+oWp16CCQwuQwkQ8rzTmrIYffGXc6RcGMSL0WKkP2xlRnqBp4In5v/FL5k1BtUBcYdt9d2s404na0KOJoVrotvxlv9F+7GZ8kh/osg/Edc9gpa3BKbRmoJ8FvOm4u2KZlgj7O5FJNO0RitQbEd96ES16sXc+L6OTEqi6natW+wOufB6sKJ2ndaFB/ffaeZ6UCk2AjQtmgpCnBF68UYfVxcnEOimJaxjEIhvLSxOL+I0cVbC+D5pePs5qtco9X7bXDkaKxIaDnhmDXhWbOCoS8iK8ZWYDU/RPSiCZZaiVBgbg+WTLSqSHB7qaR2tjcY4xoCLo4fT2Ler0ZnRx31Fi3kNC2mMeOBCNOFf4X2KLIc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
